### ISSUE TITLE
Page scrolls when pressing up or down

### ISSUE THREAD

**Issue by andylatham82** [egordorichev/pico-player#3]
This is a fantastic tool, but I notice that if embedded on a page that's large enough to have scroll bars, the page will scroll when the player presses up or down as they play a game. Is there a way to fix this?

Here's are two examples:
http://www.ladesoft.com/pages/games/babydump.html
http://www.ladesoft.com/pages/games/blackdeath.html

**Comment by egordorichev** [comment]
Thanks for the heads up, should be good now :)

**Comment by andylatham82** [comment]
Brilliant! It works! Many thanks :)
